### ISSUE TITLE
Repeat Assignment？

### ISSUE THREAD

**Issue by zxj5470** [yh200212121212/HashLib2#1]
https://github.com/yh200212121212/HashLib2/blob/917ce2451ce13968eb0b82d8967f69e58df49a0b/HashLib/HashLib.cs#L87-L90

https://github.com/yh200212121212/HashLib2/blob/917ce2451ce13968eb0b82d8967f69e58df49a0b/HashLib/HashLib.cs#L105-L108

**Comment by yh200212121212** [comment]
This isn't a good suggest,I won't agree it.
